name: Destroy Terraform
on:
    workflow_dispatch:
        inputs:
            git-ref:
                description: Git Ref (Optional)
                required: false
jobs:
    deploy:
        name: Deploy To Production
        runs-on: ubuntu-latest
        steps:                       
            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v1
              with:
                  # terraform_version: 0.13.0:
                  cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
            - name: Clone Repository (Latest)
              uses: uses: actions/checkout@v3
              if: github.event.inputs.git-ref == ''
            - name: Clone Repository (Custom Ref)
              uses: uses: actions/checkout@v3
              if: github.event.inputs.git-ref != ''
              with:
                  ref: ${{ github.event.inputs.git-ref }}
            # Now run whatever you want:
            - name: init Terraform
              working-directory: ./infra
              run: terraform init -upgrade
            - name: init Terraform
              working-directory: ./infra
              run: terraform destroy -auto-approve -input=false
